- name: Ensure AdGuard Home folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/adguard"
    state: directory

- name: Copy AdGuard Home docker compose file
  ansible.builtin.template:
    src: adguard.j2
    dest: "/home/{{ user }}/docker-containers/adguard/docker-compose.yml"

- name: Start AdGuard Home
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/adguard && docker compose down && docker compose up -d"

