- name: Ensure Gitea folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/gitea"
    state: directory

- name: Copy Gitea docker compose file
  ansible.builtin.template:
    src: gitea.j2
    dest: "/home/{{ user }}/docker-containers/gitea/docker-compose.yml"

- name: Create data directory for Gitea
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/gitea/data"
    state: directory

- name: Create config directory for Gitea
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/gitea/config"
    state: directory

- name: Start Gitea
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/gitea && docker compose down && docker compose up -d"

