- name: Ensure Homepage folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/homepage"
    state: directory

- name: Copy Homepage docker compose file
  ansible.builtin.template:
    src: homepage.j2
    dest: "/home/{{ user }}/docker-containers/homepage/docker-compose.yml"

- name: Start Homepage
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/homepage && docker compose down && docker compose up -d"

