- name: Ensure Nginx Proxy Manager folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/nginx-proxy-manager"
    state: directory

- name: Copy Nginx Proxy Manager docker compose file
  ansible.builtin.template:
    src: nginx-proxy-manager.j2
    dest: "/home/{{ user }}/docker-containers/nginx-proxy-manager/docker-compose.yml"

- name: Start Nginx Proxy Manager
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/nginx-proxy-manager && docker compose down && docker compose up -d"

