- name: Ensure Sshwifty folder exists
  ansible.builtin.file:
    path: "/home/{{ user }}/docker-containers/sshwifty"
    state: directory

- name: Copy Sshwifty docker compose file
  ansible.builtin.template:
    src: sshwifty.j2
    dest: "/home/{{ user }}/docker-containers/sshwifty/docker-compose.yml"

- name: Start Sshwifty
  ansible.builtin.shell: "cd /home/{{ user }}/docker-containers/sshwifty && docker compose down && docker compose up -d"