# This setup will use Tailscale

- name: Add Tailscale repository
  ansible.builtin.shell: "sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/rhel/9/tailscale.repo"

- name: Install Tailscale
  ansible.builtin.dnf:
    name:
      - tailscale
    state: latest
  notify: Start Tailscale service