- hosts: main

  vars_files:
    - vars.yml
    - secrets.yml

  roles:

    - role: security
      become: yes

    - role: docker
      become: yes

    # VPN configuration needed for services
    # ---
    - role: vpn
      become: yes
    # ---

    
    #- role: services